import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container:{
      flex:1,
      backgroundColor:'#00974a',
      alignItems:'center',
    },
    img:{
      width:102,
      height:112,
      marginTop:90
    },
    txtinicial:{
      marginTop:55,
      color:'white',
      fontSize:32
    },
    txtlogin:{
      fontSize:20,
  
    },
    txtsenha:{
      fontSize:20
    },
    containerInput:{
      width:278,
      height:50,
      backgroundColor:"white",
      borderRadius:14,
      marginTop:20
    },
    botaoentrar:{
      width:200,
      height:50,
      backgroundColor:"white",
      borderRadius:25,
      marginTop:20,
      fontWeight:'bold'
    },
    txtbotao:{
      fontSize:20,
      textAlign:'center',
      alignItems:'center',
      padding:10
    },
    botaocadastro:{
      width:200,
      height:50,
      backgroundColor:"white",
      borderRadius:25,
      marginTop:20,
      fontWeight:'bold'
    },
    txtbotaocadastro:{
      fontSize:20,
      textAlign:'center',
      alignItems:'center',
      padding:10
    },
    cadastroContainer:{
      flex:1,
      backgroundColor:'#00974a'
    },
    txtcadastro:{
      fontSize:36,
      color:'white',
      textAlign:'center',
      alignItems:'center',
      marginTop:25,
    },
    textInputs:{
      width:278,
      height:50,
      backgroundColor:"white",
      borderRadius:14,
      marginTop:20,
      fontSize:20
    },
    containerInputs:{
      padding:5,
      alignItems:'center',
      marginTop:2
    },
    btncadastrar:{
      width:150,
      height:45,
      backgroundColor:"white",
      borderRadius:20,
      marginBottom:45,
      alignItems:'center',
      left:120
    },
  txtcadastrar:{
    fontSize:20,
    padding:10,
    alignItems:'center',
    textAlign:'center'
  },
  viewmodal:{
    borderRadius:25,
    height:350, 
    borderRadius:15,
    width:'100%',
    backgroundColor:'white',
    height:280,
    marginTop:250

  },
  modal:{
   margin:8

  },
  txtmodal01:{
    fontSize:25,
    alignItems:'center',
    textAlign:'center',
    marginTop:25
  },
  btnmodal:{
    alignItems:'center',
    margin:45,
    backgroundColor:'green',
    borderRadius:15,
    width:300,
    height:30
  },
  txtmodal02:{
    alignItems:'center',
    textAlign:'center',
    fontSize:20,
    fontWeight:'bold'
  },
  imgmodal:{
    width:80,
    height:80,
    marginBottom:20,
    left:150,
    marginTop:25
  },
  containerHome:{
    flex:1,
    backgroundColor:'#00974a',
  },
  imgLogoHome:{
    width:62,
    height:62
  },
  imgContainerHome:{
    padding:20
  },
  txtHome:{
    alignItems:'center',
    textAlign:'center',
    marginTop:30,
    color:'white',
    fontSize:48
  },
  containerBtn:{
    flexDirection:'row',
    flexWrap:'wrap',
    marginTop:10,
    padding:15,

  },
  imgbtn:{
    width:150,
    height:150,
    marginTop:5
  },
  Principal01:{
    backgroundColor:'white',
    borderRadius:14,
    padding:2,
    alignItems:'center',
    marginBottom:25,
    marginRight:8
  },
  Principal02:{
    backgroundColor:'white',
    borderRadius:14,
    padding:2,
    alignItems:'center',
    marginBottom:25,
    marginLeft:6
    
  },
  Principal03:{
    backgroundColor:'white',
    borderRadius:14,
    padding:2,
    alignItems:'center',
    marginRight:8
  },
  Principal04:{
    backgroundColor:'white',
    borderRadius:14,
    padding:2,
    alignItems:'center',
    marginLeft:6
  },
  txtbtnPrincipal:{
    fontSize:15,
    textAlign:'center',
    fontWeight:'bold'
  },
  txtcontainerPadrao:{
    color:'white',
    textAlign:'center',
    padding:30,
    fontSize:48
  },
  containercentralPadrao:{
    alignItems:'center'
  },
  imgcontainerPadrao:{
    height:50,
    width:52,
    backgroundColor:'white',
    borderRadius:8
    
  },
  txtsegmento:{
    color:'white',
    marginTop:15,
    fontSize:24
  },
  imgsegmentos:{
    height:80,
    width:'95%',
    borderRadius:10,
    left:10,
    marginTop:10
  },
  txtsegmentos:{
    textAlign:'center',
    fontWeight:'500',
    fontSize:30,
    marginTop:-60,
  },
  btnSegmentos01:{
    
  },
  btnSegmentos02:{
    marginTop: 30
  },
  btnSegmentos03:{
    marginTop: 30
  },
  btnSegmentos04:{
    marginTop: 30
  },
  containerRedeSocial:{
    alignItems:'center',
    backgroundColor:'white',
    marginTop:20,
    height:'18%',
    width:'30%',
    left:140,
    borderRadius:10
  }

  })  

  export default styles;