import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container:{
      flex:1,
      backgroundColor:'#00974a',
      alignItems:'center',
    },
    img:{
      width:102,
      height:112,
      marginTop:90
    },
    txtinicial:{
      marginTop:55,
      color:'white',
      fontSize:32
    },
    txtlogin:{
      fontSize:20,
  
    },
    txtsenha:{
      fontSize:20
    },
    containerInput:{
      width:278,
      height:50,
      backgroundColor:"white",
      borderRadius:14,
      marginTop:20
    },
    botaoentrar:{
      width:200,
      height:50,
      backgroundColor:"white",
      borderRadius:25,
      marginTop:20,
      fontWeight:'bold'
    },
    txtbotao:{
      fontSize:20,
      textAlign:'center',
      alignItems:'center',
      padding:10
    },
    botaocadastro:{
      width:200,
      height:50,
      backgroundColor:"white",
      borderRadius:25,
      marginTop:20,
      fontWeight:'bold'
    },
    txtbotaocadastro:{
      fontSize:20,
      textAlign:'center',
      alignItems:'center',
      padding:10
    },
    cadastroContainer:{
      flex:1,
      backgroundColor:'#00974a'
    },
    txtcadastro:{
      fontSize:36,
      color:'white',
      textAlign:'center',
      alignItems:'center',
      marginTop:25,
    },
    textInputs:{
      width:278,
      height:50,
      backgroundColor:"white",
      borderRadius:14,
      marginTop:20,
      fontSize:20
    },
    containerInputs:{
      padding:5,
      alignItems:'center',
      marginTop:2
    },
    btncadastrar:{
      width:150,
      height:45,
      backgroundColor:"white",
      borderRadius:20,
      marginBottom:45,
      alignItems:'center',
      left:120
    },
  txtcadastrar:{
    fontSize:20,
    padding:10,
    alignItems:'center',
    textAlign:'center'
  },
  viewmodal:{
    borderRadius:25,
    height:350, 
    borderRadius:15,
    width:'100%',
    backgroundColor:'white',
    height:280,
    marginTop:250

  },
  modal:{
   margin:8

  },
  txtmodal01:{
    fontSize:25,
    alignItems:'center',
    textAlign:'center',
    marginTop:25
  },
  btnmodal:{
    alignItems:'center',
    margin:45,
    backgroundColor:'green',
    borderRadius:15,
    width:300,
    height:30
  },
  txtmodal02:{
    alignItems:'center',
    textAlign:'center',
    fontSize:20,
    fontWeight:'bold'
  },
  imgmodal:{
    width:80,
    height:80,
    marginBottom:20,
    left:150,
    marginTop:25
  }


  
  })  

  export default styles;